import torch
from dataset import *

DEVICE = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
SEED = 2333


class DATASET_MNIST:
    DS = MnistDataset
    DIR = "../DATASET/"
    IMAGE_SIZE = 28
    IMAGE_CHANNELS = 1


DATASET = DATASET_MNIST
IMAGE_SIZE = DATASET.IMAGE_SIZE
IMAGE_CHANNELS = DATASET.IMAGE_CHANNELS

BATCH_SIZE = 64
SAMPLE_SIZE = 8**2
LR = 3e-4
NOISE_DIM = 128
NUM_EPOCHS = 50

LOG_WIGHT = True
LOG_GRADIENT = True

LOG_INTERVAL = 10
TEST_INTERVAL = 100
LOG_HISTOGRAM_INTERVAL = 100
