import torch
from dataset import *

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
SEED = 2333
RESTORE_CKPT_PATH = None


class DATASET_MNIST:
    DS = MnistDataset
    DIR = "../DATASET/"
    IMAGE_SIZE = 64
    IMAGE_CHANNELS = 1
    NUM_CLASSES = 10


class DATASET_FMNIST(DATASET_MNIST):
    DS = FashionMNISTDataset


class DATASET_CIFAR10(DATASET_MNIST):
    DS = Cifar10Dataset
    IMAGE_CHANNELS = 3


DATASET = DATASET_MNIST
IMAGE_SIZE = DATASET.IMAGE_SIZE
IMAGE_CHANNELS = DATASET.IMAGE_CHANNELS
NUM_CLASSES = DATASET.NUM_CLASSES

BATCH_SIZE = 64
NOISE_DIM = 100
EMBEDDING_SIZE = 100
SAMPLE_SIZE = 100
GEN_DIM = 64
DISC_DIM = 64
NUM_EPOCHS = 10

LEARNING_RATE = 2e-4
BETAS = (0.5, 0.999)

LOG_INTERVAL = 10
TEST_INTERVAL = 10000
