import torch

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
SEED = 2333


class DATASET_MNIST:
    CAT = "mnist"
    DIR = "../dataset/"
    IMAGE_SIZE = 64
    IMAGE_CHANNELS = 1


class DATASET_CELABA(DATASET_MNIST):
    CAT = "celaba"
    DIR = ""
    IMAGE_SIZE = 64
    IMAGE_CHANNELS = 3


DATASET = DATASET_MNIST
IMAGE_SIZE = DATASET.IMAGE_SIZE
IMAGE_CHANNELS = DATASET.IMAGE_CHANNELS

BATCH_SIZE = 64
NOISE_DIM = 128
GEN_DIM = 64
DISC_DIM = 64

NUM_EPOCHS = 10
LEARNING_RATE = 5e-5
CRITIC_ITERATIONS = 5
WEIGHT_CLIP = 0.01

LOG_INTERVAL = 10
TEST_INTERVAL = 100
